from __future__ import annotations

from dataclasses import dataclass

import requests


@dataclass
class GenerationResult:
    """
    Represents the result generated by the LLM.
    """

    query: str
    answer: str
    model: str


class LLMGenerator:
    """
    Generates grounded answers using a local Ollama model.

    The generator receives already-retrieved context.
    It does not perform retrieval itself.
    """

    DEFAULT_MODEL = "llama3.2"

    def __init__(
        self,
        model: str = DEFAULT_MODEL,
        base_url: str = "http://localhost:11434",
        timeout: int = 120,
    ) -> None:

        self.model = model
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout

    def generate(
        self,
        query: str,
        context: str,
    ) -> GenerationResult:
        """
        Generate an answer using only the supplied context.
        """

        query = query.strip()
        context = context.strip()

        if not query:
            raise ValueError(
                "Query cannot be empty."
            )

        if not context:
            raise ValueError(
                "Context cannot be empty."
            )

        prompt = self._build_prompt(
            query=query,
            context=context,
        )

        response = requests.post(
            f"{self.base_url}/api/generate",
            json={
                "model": self.model,
                "prompt": prompt,
                "stream": False,
            },
            timeout=self.timeout,
        )

        response.raise_for_status()

        data = response.json()

        answer = data.get(
            "response",
            "",
        ).strip()

        if not answer:
            raise RuntimeError(
                "Ollama returned an empty response."
            )

        return GenerationResult(
            query=query,
            answer=answer,
            model=self.model,
        )

    def _build_prompt(
        self,
        query: str,
        context: str,
    ) -> str:
        """
        Build a grounded RAG prompt.

        The model is explicitly instructed not to
        invent information outside the retrieved context.
        """

        return f"""
You are ResearchPilot, an AI research assistant.

Answer the user's question using ONLY the research
context provided below.

Rules:
1. Do not use information that is not supported by
   the provided context.
2. Do not invent facts, results, citations, or numbers.
3. If the context does not contain enough information
   to answer the question, say so clearly.
4. Give a concise and direct answer.
5. Preserve important technical terminology.
6. When useful, mention the relevant section or source
   information provided in the context.

USER QUESTION:
{query}

RESEARCH CONTEXT:
{context}

ANSWER:
""".strip()