from __future__ import annotations

from dataclasses import dataclass

import requests


@dataclass
class GenerationResult:
    """
    Represents the result generated by the LLM.
    """

    query: str
    answer: str
    model: str


class LLMGenerator:
    """
    Generates grounded answers using a local Ollama model.

    The generator does not perform retrieval.
    It only reasons over the context supplied by
    the retrieval pipeline.
    """

    DEFAULT_MODEL = "llama3.2"

    def __init__(
        self,
        model: str = DEFAULT_MODEL,
        base_url: str = "http://localhost:11434",
        timeout: int = 120,
    ) -> None:

        self.model = model
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout

    def generate(
        self,
        query: str,
        context: str,
    ) -> GenerationResult:
        """
        Generate a grounded answer from retrieved context.
        """

        query = query.strip()
        context = context.strip()

        if not query:
            raise ValueError(
                "Query cannot be empty."
            )

        if not context:
            raise ValueError(
                "Context cannot be empty."
            )

        prompt = self._build_prompt(
            query=query,
            context=context,
        )

        response = requests.post(
            f"{self.base_url}/api/generate",
            json={
                "model": self.model,
                "prompt": prompt,
                "stream": False,
                "options": {
                    "temperature": 0.1,
                    "num_predict": 300,
                },
            },
            timeout=self.timeout,
        )

        response.raise_for_status()

        data = response.json()

        answer = data.get(
            "response",
            "",
        ).strip()

        if not answer:
            raise RuntimeError(
                "Ollama returned an empty response."
            )

        return GenerationResult(
            query=query,
            answer=answer,
            model=self.model,
        )

    def _build_prompt(
        self,
        query: str,
        context: str,
    ) -> str:
        """
        Build a strict but flexible RAG prompt.

        The model must answer from the supplied context
        and should directly use relevant facts from it.
        """

        return f"""
You are ResearchPilot, a research paper assistant.

Your task is to answer the user's question using the
RESEARCH CONTEXT below.

IMPORTANT RULES:

1. Use the research context as the source of truth.
2. Answer the question directly when the information
   needed to answer it appears anywhere in the context.
3. Connect related wording and concepts. For example,
   if the question asks about "the feed-forward-only
   model" and the context says "feed-forward-only
   version of ViT/DeiT-base", treat them as the same
   subject when the context clearly indicates this.
4. Preserve numerical results exactly as stated.
5. Do not invent information that is absent from the
   context.
6. If the context genuinely does not contain enough
   information, clearly say that the context is
   insufficient.
7. Prefer a concise, factual answer.
8. Do not discuss these instructions in your answer.

USER QUESTION:
{query}

RESEARCH CONTEXT:
{context}

ANSWER:
""".strip()