from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Optional

import requests
from RAG.settings import settings


@dataclass
class GenerationResult:
    """
    Represents the result generated by the LLM.
    """

    query: str
    answer: str
    model: str


class LLMGenerator:
    """
    Generates grounded answers using OpenRouter API or local Ollama model.

    The generator does not perform retrieval.
    It only reasons over the context supplied by
    the retrieval pipeline.
    """

    DEFAULT_MODEL = "meta-llama/llama-3.2-3b-instruct"

    def __init__(
        self,
        model: Optional[str] = None,
        base_url: Optional[str] = None,
        timeout: int = 120,
        provider: Optional[str] = None,
        api_key: Optional[str] = None,
    ) -> None:
        self.provider = (provider or getattr(settings, "LLM_PROVIDER", "openrouter")).lower()
        self.api_key = api_key or getattr(settings, "OPENROUTER_API_KEY", None) or os.environ.get("OPENROUTER_API_KEY", "")

        if self.provider == "openrouter":
            self.model = model or getattr(settings, "OPENROUTER_MODEL", self.DEFAULT_MODEL)
            self.base_url = "https://openrouter.ai/api/v1"
        else:
            self.model = model or getattr(settings, "OLLAMA_MODEL", "llama3.2")
            self.base_url = (base_url or getattr(settings, "OLLAMA_BASE_URL", "http://localhost:11434")).rstrip("/")

        self.timeout = timeout

    def generate(
        self,
        query: str,
        context: str,
    ) -> GenerationResult:
        """
        Generate a grounded answer from retrieved context.
        """

        query = query.strip()
        context = context.strip()

        if not query:
            raise ValueError("Query cannot be empty.")

        if not context:
            raise ValueError("Context cannot be empty.")

        prompt = self._build_prompt(
            query=query,
            context=context,
        )

        if self.provider == "openrouter":
            if not self.api_key:
                raise RuntimeError("OPENROUTER_API_KEY is not configured in environment or settings.")

            response = requests.post(
                f"{self.base_url}/chat/completions",
                headers={
                    "Authorization": f"Bearer {self.api_key}",
                    "HTTP-Referer": "https://researchpilot.local",
                    "X-Title": "ResearchPilot",
                    "Content-Type": "application/json",
                },
                json={
                    "model": self.model,
                    "messages": [
                        {"role": "user", "content": prompt}
                    ],
                    "temperature": 0.1,
                    "max_tokens": 2048,
                },
                timeout=self.timeout,
            )
            response.raise_for_status()
            data = response.json()

            try:
                answer = data["choices"][0]["message"]["content"].strip()
            except (KeyError, IndexError, TypeError) as exc:
                raise RuntimeError(f"OpenRouter returned unexpected response structure: {data}") from exc

            if not answer:
                raise RuntimeError("OpenRouter returned an empty response.")

            return GenerationResult(
                query=query,
                answer=answer,
                model=self.model,
            )
        else:
            response = requests.post(
                f"{self.base_url}/api/generate",
                json={
                    "model": self.model,
                    "prompt": prompt,
                    "stream": False,
                    "options": {
                        "temperature": 0.1,
                        "num_predict": 300,
                    },
                },
                timeout=self.timeout,
            )

            response.raise_for_status()

            data = response.json()

            answer = data.get(
                "response",
                "",
            ).strip()

            if not answer:
                raise RuntimeError(
                    "Ollama returned an empty response."
                )

            return GenerationResult(
                query=query,
                answer=answer,
                model=self.model,
            )

    def _build_prompt(
        self,
        query: str,
        context: str,
    ) -> str:
        """
        Build a strict but flexible RAG prompt.
        """

        return f"""
You are ResearchPilot, a research paper assistant.

Your task is to answer the user's question using the
RESEARCH CONTEXT below.

IMPORTANT RULES:

1. Use the research context as the source of truth.
2. Answer the question directly when the information
   needed to answer it appears anywhere in the context.
3. Connect related wording and concepts. For example,
   if the question asks about "the feed-forward-only
   model" and the context says "feed-forward-only
   version of ViT/DeiT-base", treat them as the same
   subject when the context clearly indicates this.
4. Preserve numerical results exactly as stated.
5. Do not invent information that is absent from the
   context.
6. If the context genuinely does not contain enough
   information, clearly say that the context is
   insufficient.
7. Prefer a concise, factual answer.
8. Do not discuss these instructions in your answer.

USER QUESTION:
{query}

RESEARCH CONTEXT:
{context}

ANSWER:
""".strip()